name: event_timeline_view
version: 0.0.3
description: An event timeline view allows users to visualize the occurrence and
  sequence of events over time and understanding of future occurrences.
homepage: https://jarvistechnolabs.com/
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_size_text: ^3.0.0
  flutter:
    sdk: flutter
  intl: ^0.18.0
  table_calendar: ^3.0.4

dev_dependencies:
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/images/
